### ISSUE TITLE
pamela -i cannot read from current working dir but used to !

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#33]
Following command line used to work but not anymore.

ls -l biased-coin.pamela 
-rw-r--r--  1 ...  staff  2286 Nov  9 14:00 biased-coin.pamela
 ~/p/p/demo-nov-2016-pamela> pamela -i biased-coin.pamela -o biased-coin.1000-flips.tpn.json --construct-tpn main:flip-sequence:flip-1000 -f json tpn
16-11-09 19:03:58 prakash-retina ERROR [pamela.cli:0] - 
 Failed to validate "-i biased-coin.pamela": INPUT file does not exist

Probabalistic Advanced Modeling and Execution Learning Architecture (PAMELA)

Usage: pamela [options] action

**Comment by tmarble** [comment]
@pmdoll cannot reproduce.

Are you sure that
1. `which pamela` refers to `./bin/pamela` in the repository you intend it to?
2. Is that repository up-to-date (e.g. `git pull`)?
3. Has the uberjar been created since step #2 (`lein uberjar`)? NOTE: since the default mode is now production an existing uberjar will be used immediately and *not* checked to see if it is out of date relative to the source.

**Comment by pmdoll** [comment]
1. pamela refers to pamela/bin
2. In a top-level-dir, I do
`(cd pamela/; git pull; lein clean; lein uberjar)`
